name: conceptarium
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.*

  - pytorch:pytorch
  - pytorch:pytorch-cuda
  - torchvision>=0.17.1
  - torchmetrics>=0.7

  - lightning
  - hydra-core
  - wandb
  - numpy
  - pandas==2.2.*
  - pytables
  - tqdm
  - scikit-learn
  - scipy
  - tqdm
  - openpyxl

  - pip
  - pip:
    - bnlearn # library for Bayesian networks
    - gdown # to download files from Google Drive (CelebA dataset)
    - transformers # State-of-the-art pretrained models for backbones
    - hydra-list-sweeper