name: conceptarium
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.*

  # PyTorch for macOS Silicon (uses MPS backend for GPU acceleration)
  - pytorch::pytorch
  - pytorch::torchvision>=0.17.1
  - torchmetrics>=0.7

  # Image processing libraries required by torchvision
  - conda-forge::jpeg
  
  - lightning
  - hydra-core
  - wandb
  - numpy
  - pandas==2.2.*
  - pytables
  - tqdm
  - scikit-learn
  - scipy
  - openpyxl

  - pip
  - pip:
    - bnlearn # library for Bayesian networks
    - transformers # State-of-the-art pretrained models for backbones
    - hydra-list-sweeper
